#!/bin/bash

# Default params
export acqusetup="CylMwpc.Offline" # AcquRoot setup
export nproc=1 #proc to run in parallel
export outdir="mwpc_calib" # output dir inside ./out

# Input params
# TODO better options parsing
if [ $# -ge 1 ]; then
  nproc=$1
fi
if [ $# -ge 2 ]; then
  acqusetup=$2
fi
if [ $# -ge 3 ]; then
  outdir=$3
fi

#_______________________________________________________________________
runCalib()
{
  out=./out/$outdir/step$2_correction$1
  run_AcquRoot . $acqusetup $out $nproc
  hadd -f nsummed.root $out/*_hist.root
  root -l -b -q AutoCalibMwpc.C"($1)" # creates a new mwpc_params.dat
}

#_______________________________________________________________________
# Find MWPC config file
analysis_setup=`cat ./data/$acqusetup | grep "^AnalysisSetup:" | awk '{print $2}'`
cb_setup=`cat ${analysis_setup} | grep "^Apparatus:" | grep "TA2CentralApparatus" | awk '{print $4}'`
mwpc_setup=`cat ${cb_setup} | grep "^Detector:" | grep "TA2CylMwpc" | awk '{print $4}'`

#_______________________________________________________________________
# Run calibs
list_calibs="0 0 1 1 1 3 4 5"
step=0
for i in ${list_calibs}
do
  cat ${mwpc_setup} | grep "^Intersection:" | sed 's/Intersection:[ \t]*//' > mwpc_params.dat # prepare mwpc_params.dat for AutoCalibMwpc.C
  let 'step +=1'
  runCalib $i $step
  sed -i 's/^Intersection:/# Intersection:/g' ${mwpc_setup} # comment old Intersect:
  sed -i '/^END/d' ${mwpc_setup} # delete END
  echo "# After AutoCalibMwpc.C($i)" >> ${mwpc_setup}
  while read line # Adding corrections
  do
    echo "Intersection: $line" >> ${mwpc_setup}
  done < mwpc_params.dat
  echo >> ${mwpc_setup}
  echo "END" >> ${mwpc_setup}
done

#_______________________________________________________________________
# Calibrated result
out=./out/$outdir/calibrated
run_AcquRoot . $acqusetup $out $nproc
hadd -f nsummed.root $out/*_hist.root
